import React, { useEffect, useState } from "react";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Headless from "../components/Headless";
import ReactMain from "../components/ReactMain";
import ReactWhoUses from "../components/ReactWhoUses";
import Vue from "../components/Vue";
import EaseofDevelopment from "../components/EaseofDevelopment";
import Costs from "../components/Costs";
import Conclusion from "../components/Conclusion";
import Thanks from "../components/Thanks";
import Button from "../components/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const slideCSS =
		"d-flex flex-column justify-content-stretch vw-100 vh-100 min-vw-100 min-vh-100";

	const [currentNum, setCurrentNum] = useState(0);
	const slides = [
		Headless,
		ReactMain,
		ReactWhoUses,
		Vue,
		EaseofDevelopment,
		Costs,
		Conclusion,
		Thanks,
	];

	let CurrentSlide = slides[currentNum];

	const prevSlide = () => {
		if (currentNum >= 1) {
			setCurrentNum(currentNum - 1);
		}
	};

	const nextSlide = () => {
		if (currentNum < slides.length - 1) {
			setCurrentNum(currentNum + 1);
		}
	};

	const handleKeyPress = (e) => {
		if (e.key === "ArrowRight") {
			nextSlide();
		} else if (e.key === "ArrowLeft") {
			prevSlide();
		}
	};

	const h1CSS = "h1 text-uppercase mb-0";
	const slideContainerCSS =
		"d-flex flex-column h-100  display-6 overflow-scroll p-5";

	return (
		<>
			<Head>
				<title>
					Exploring Front-End Web Development with React by Todd Heckeler
				</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div
				className="d-flex flex-column justify-content-stretch vw-100 vh-100 min-vw-100 min-vh-100 user-select-none"
				onKeyDown={handleKeyPress}
				tabIndex="0">
				<main
					className="flex-grow-1 overflow-hidden position-relative"
					style={{ background: "#bbf272" }}>
					<div
						className="position-absolute overflow-hidden"
						style={{ top: 0, left: 0, zIndex: 0 }}>
						<ul
							className="d-flex flex-column list-unstyled mb-0 list-unstyled"
							style={{ transform: `translateY(-${currentNum}00vh)` }}>
							<li className="position-relative vw-100 vh-100">
								<Image
									src="https://static.wikia.nocookie.net/harrypotter/images/b/b6/Nick_in_Great_Hall.jpg"
									alt=""
									fill
									style={{ objectFit: "cover" }}
								/>
							</li>
							<li className="position-relative vw-100 vh-100">
								<Image
									src="https://www.freecodecamp.org/news/content/images/size/w2000/2022/03/photo-1619410283995-43d9134e7656.jpeg"
									alt=""
									fill
									style={{ objectFit: "cover" }}
								/>
							</li>
							<li className="position-relative vw-100 vh-100">
								<Image
									src="https://www.freecodecamp.org/news/content/images/size/w2000/2022/03/photo-1619410283995-43d9134e7656.jpeg"
									alt=""
									fill
									style={{ objectFit: "cover" }}
								/>
							</li>
							<li className="position-relative vw-100 vh-100">
								<Image
									src="https://www.freecodecamp.org/news/content/images/size/w2000/2022/03/photo-1619410283995-43d9134e7656.jpeg"
									alt=""
									fill
									style={{ objectFit: "cover" }}
								/>
							</li>
							<li className="position-relative vw-100 vh-100">
								<Image
									src="https://www.freecodecamp.org/news/content/images/size/w2000/2022/03/photo-1619410283995-43d9134e7656.jpeg"
									alt=""
									fill
									style={{ objectFit: "cover" }}
								/>
							</li>
							<li className="position-relative vw-100 vh-100">
								<Image
									src="https://www.freecodecamp.org/news/content/images/size/w2000/2022/03/photo-1619410283995-43d9134e7656.jpeg"
									alt=""
									fill
									style={{ objectFit: "cover" }}
								/>
							</li>
							<li className="position-relative vw-100 vh-100">
								<Image
									src="https://www.freecodecamp.org/news/content/images/size/w2000/2022/03/photo-1619410283995-43d9134e7656.jpeg"
									alt=""
									fill
									style={{ objectFit: "cover" }}
								/>
							</li>
							<li className="position-relative vw-100 vh-100">
								<Image
									src="https://www.freecodecamp.org/news/content/images/size/w2000/2022/03/photo-1619410283995-43d9134e7656.jpeg"
									alt=""
									fill
									style={{ objectFit: "cover" }}
								/>
							</li>
						</ul>
					</div>
					<div
						className="container h-100 d-flex flex-column justify-content-stretch p-5 position-relative"
						style={{ background: "rgba(255,255,255,0.85)", zIndex: 1 }}>
						<CurrentSlide {...{ slideContainerCSS, h1CSS }} />
					</div>
				</main>

				<nav className="p-2" style={{ background: "#47a1e6" }}>
					<ul className="container d-flex align-items-center list-unstyled mb-0">
						<li className="col-4">
							<Button
								{...{ currentNum, slides }}
								whichWay={prevSlide}
								copy="«"
								isDisabled={currentNum === 0 ? true : false}
							/>
						</li>
						<li className="col-4 text-center text-uppercase text-white">
							Slide: {currentNum + 1} / {slides.length}
						</li>
						<li className="col-4 text-end">
							<Button
								{...{ currentNum, slides }}
								whichWay={nextSlide}
								copy="»"
								isDisabled={currentNum === slides.length - 1 ? true : false}
							/>
						</li>
					</ul>
				</nav>
			</div>
		</>
	);
}
