import React, { useEffect, useState } from "react";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Slide1 from "../components/Slide1";
import Slide2 from "../components/Slide2";
import Slide3 from "../components/Slide3";
import Slide4 from "../components/Slide4";
import Slide5 from "../components/Slide5";
import Slide6 from "../components/Slide6";
import Slide7 from "../components/Slide7";
import Slide8 from "../components/Slide8";
import Button from "../components/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const slideCSS =
		"d-flex flex-column justify-content-stretch vw-100 vh-100 min-vw-100 min-vh-100";

	const [currentNum, setCurrentNum] = useState(0);
	const slides = [
		Slide1,
		Slide2,
		Slide3,
		Slide4,
		Slide5,
		Slide6,
		Slide7,
		Slide8,
	];

	let CurrentSlide = slides[currentNum];

	const prevSlide = () => {
		if (currentNum >= 1) {
			setCurrentNum(currentNum - 1);
		}
	};

	const nextSlide = () => {
		if (currentNum < slides.length - 1) {
			setCurrentNum(currentNum + 1);
		}
	};

	const handleKeyPress = (e) => {
		if (e.key === "ArrowRight") {
			nextSlide();
		} else if (e.key === "ArrowLeft") {
			prevSlide();
		}
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div
				className="d-flex flex-column justify-content-stretch vw-100 vh-100 min-vw-100 min-vh-100"
				onKeyDown={handleKeyPress}
				tabIndex="0">
				<main
					className="flex-grow-1 overflow-hidden position-relative"
					style={{ background: "#bbf272" }}>
					<div
						className="position-absolute overflow-hidden"
						style={{ top: 0, left: 0, zIndex: 0 }}>
						<ul className="d-flex flex-column list-unstyled mb-0 list-unstyled">
							<li className="position-relative vw-100 vh-100">
								<Image
									src="https://static.wikia.nocookie.net/harrypotter/images/b/b6/Nick_in_Great_Hall.jpg"
									alt=""
									fill
									style={{ objectFit: "cover" }}
								/>
							</li>
						</ul>
					</div>
					<div
						className="container h-100 d-flex flex-column justify-content-stretch p-5 position-relative"
						style={{ background: "rgba(255,255,255,0.85)", zIndex: 1 }}>
						<CurrentSlide />
					</div>
				</main>

				<nav className="p-2" style={{ background: "#47a1e6" }}>
					<ul className="container d-flex list-unstyled mb-0">
						<li className="">
							<Button whichWay={prevSlide} copy="«" />
						</li>
						<li className="ms-auto">
							<Button whichWay={nextSlide} copy="»" />
						</li>
					</ul>
				</nav>
			</div>
		</>
	);
}
